### ISSUE TITLE
Cannot build TypeScript project

### ISSUE THREAD

**Issue by kerolloz** [aravindnc/mongoose-paginate-v2#155] opened 2022-02-04 10:57 UTC
**Describe the bug**
build errors when using typescript

**To Reproduce**
1. `npm i mongoose-paginate-v2`
2. build with `tsc`
**Screenshots**
![image](https://user-images.githubusercontent.com/36763164/152517193-c1d68d81-082d-483b-9b85-11357648c747.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version :  "mongoose-paginate-v2": "^1.6.0",

**Comment by aravindnc** [comment] 2022-02-04 13:13
@ypicard Any idea what is wrong.

**Comment by ypicard** [comment] 2022-02-04 15:54
Will look today.

**Comment by ypicard** [comment] 2022-02-04 18:07
@kerolloz I cannot reproduce your issue.

`mongoose@5.13.2` is a required dependency for this package. Do you have it installed in the correct version?

Could you link to a project where I can reproduce the problem?

**Comment by kerolloz** [comment] 2022-02-04 18:22
Hmm, I believe I have a different version `"mongoose": "^6.1.9"`

I will try `mongoose@5.13.2`

**Comment by ypicard** [comment] 2022-02-04 18:27
Yes, it seems this package does not support `mongoose@6` - but I do not know what the requirements for supporting it would be.

Could be an issue of its own.

**Comment by ypicard** [comment] 2022-02-07 23:09
@aravindnc You can probably close this.

**Comment by orgads** [comment] 2022-02-08 08:53
Why? Please add support for mongoose 6.

**Comment by ypicard** [comment] 2022-02-08 17:13
Because this is not the topic of this issue.

Would you like to give it a shot and send a PR for mongoose 6?

**Comment by aravindnc** [comment] 2022-02-09 09:54
I will add a separate issue for mongoose 6.

**Closed by aravindnc** 2022-02-09 09:54 UTC
Labels: bug
